'use client';

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { AlertCircle, TrendingUp, Zap, Shield, AlertTriangle, Bell } from 'lucide-react';

interface Alert {
  id: string;
  timestamp: number;
  type: 'info' | 'warning' | 'critical' | 'success';
  category: 'price' | 'volume' | 'spread' | 'flow' | 'regime' | 'anomaly';
  title: string;
  message: string;
  metadata?: {
    value?: number;
    change?: number;
    threshold?: number;
  };
}

interface AlertFeedProps {
  maxAlerts?: number;
  autoGenerateDemo?: boolean;
}

export function AlertFeed({ maxAlerts = 50, autoGenerateDemo = true }: AlertFeedProps) {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [filter, setFilter] = useState<string>('all');

  // Demo alert generation
  useEffect(() => {
    if (!autoGenerateDemo) return;

    const demoAlerts: Alert[] = [
      {
        id: '1',
        timestamp: Date.now() - 5000,
        type: 'warning',
        category: 'spread',
        title: 'Spread Widening',
        message: 'Bid-ask spread increased to 12.5 bps (threshold: 10 bps)',
        metadata: { value: 12.5, threshold: 10 },
      },
      {
        id: '2',
        timestamp: Date.now() - 15000,
        type: 'critical',
        category: 'flow',
        title: 'High VPIN Detected',
        message: 'VPIN reached 0.72, indicating potential toxicity in order flow',
        metadata: { value: 0.72, threshold: 0.7 },
      },
      {
        id: '3',
        timestamp: Date.now() - 30000,
        type: 'info',
        category: 'regime',
        title: 'Regime Change',
        message: 'Market regime shifted from mean-reverting to trending',
      },
      {
        id: '4',
        timestamp: Date.now() - 60000,
        type: 'success',
        category: 'price',
        title: 'Price Target Reached',
        message: 'BTC/USDT reached resistance at $45,000',
        metadata: { value: 45000 },
      },
    ];

    setAlerts(demoAlerts);

    // Generate new alerts periodically
    const interval = setInterval(() => {
      const alertTemplates = [
        {
          type: 'warning' as const,
          category: 'volume' as const,
          title: 'Volume Spike',
          message: `${Math.random() > 0.5 ? 'Buy' : 'Sell'} volume increased by ${(20 + Math.random() * 30).toFixed(1)}%`,
        },
        {
          type: 'critical' as const,
          category: 'anomaly' as const,
          title: 'Anomaly Detected',
          message: 'Unusual order pattern detected - possible spoofing activity',
        },
        {
          type: 'info' as const,
          category: 'spread' as const,
          title: 'Spread Normalized',
          message: `Spread returned to normal range (${(5 + Math.random() * 3).toFixed(1)} bps)`,
        },
        {
          type: 'warning' as const,
          category: 'flow' as const,
          title: 'Order Imbalance',
          message: `Heavy ${Math.random() > 0.5 ? 'buying' : 'selling'} pressure detected`,
        },
      ];

      const template = alertTemplates[Math.floor(Math.random() * alertTemplates.length)];
      const newAlert: Alert = {
        ...template,
        id: Math.random().toString(36).substr(2, 9),
        timestamp: Date.now(),
      };

      setAlerts(prev => [newAlert, ...prev].slice(0, maxAlerts));
    }, 8000);

    return () => clearInterval(interval);
  }, [autoGenerateDemo, maxAlerts]);

  const getAlertIcon = (category: string) => {
    switch (category) {
      case 'price':
        return <TrendingUp className="w-4 h-4" />;
      case 'volume':
        return <Zap className="w-4 h-4" />;
      case 'spread':
        return <Shield className="w-4 h-4" />;
      case 'flow':
        return <AlertCircle className="w-4 h-4" />;
      case 'anomaly':
        return <AlertTriangle className="w-4 h-4" />;
      default:
        return <Bell className="w-4 h-4" />;
    }
  };

  const getAlertColor = (type: string) => {
    switch (type) {
      case 'critical':
        return 'bg-red-500/10 border-red-500/30 text-red-400';
      case 'warning':
        return 'bg-yellow-500/10 border-yellow-500/30 text-yellow-400';
      case 'success':
        return 'bg-green-500/10 border-green-500/30 text-green-400';
      default:
        return 'bg-blue-500/10 border-blue-500/30 text-blue-400';
    }
  };

  const getBadgeColor = (type: string) => {
    switch (type) {
      case 'critical':
        return 'bg-red-500/20 text-red-300';
      case 'warning':
        return 'bg-yellow-500/20 text-yellow-300';
      case 'success':
        return 'bg-green-500/20 text-green-300';
      default:
        return 'bg-blue-500/20 text-blue-300';
    }
  };

  const formatTime = (timestamp: number) => {
    const date = new Date(timestamp);
    const now = new Date();
    const diff = Math.floor((now.getTime() - date.getTime()) / 1000);

    if (diff < 60) return `${diff}s ago`;
    if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
    if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
    return date.toLocaleTimeString();
  };

  const filteredAlerts = filter === 'all'
    ? alerts
    : alerts.filter(alert => alert.type === filter);

  return (
    <div className="bg-zinc-900 rounded-lg border border-zinc-800">
      <div className="p-4 border-b border-zinc-800">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <AlertCircle className="w-4 h-4 text-blue-500" />
            <h3 className="text-sm font-semibold text-white">Alert Feed</h3>
          </div>
          <span className="text-xs text-zinc-500">
            {filteredAlerts.length} alerts
          </span>
        </div>

        {/* Filter Buttons */}
        <div className="flex gap-1">
          {['all', 'critical', 'warning', 'info'].map(filterType => (
            <button
              key={filterType}
              onClick={() => setFilter(filterType)}
              className={`
                px-2 py-1 text-xs rounded transition-all duration-200
                ${filter === filterType
                  ? 'bg-blue-500/20 text-blue-400'
                  : 'text-zinc-500 hover:text-zinc-300 hover:bg-zinc-800'
                }
              `}
            >
              {filterType.charAt(0).toUpperCase() + filterType.slice(1)}
            </button>
          ))}
        </div>
      </div>

      <div className="max-h-[600px] overflow-y-auto">
        <AnimatePresence mode="popLayout">
          {filteredAlerts.map((alert, index) => (
            <motion.div
              key={alert.id}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 20 }}
              transition={{ duration: 0.2, delay: index * 0.02 }}
              className={`
                p-3 border-b border-zinc-800/50 transition-all duration-200
                hover:bg-zinc-800/30 cursor-pointer group
              `}
            >
              <div className="flex items-start gap-3">
                <div className={`
                  p-1.5 rounded-lg ${getAlertColor(alert.type)}
                `}>
                  {getAlertIcon(alert.category)}
                </div>

                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <h4 className="text-xs font-medium text-white">
                          {alert.title}
                        </h4>
                        <span className={`
                          px-1.5 py-0.5 text-[10px] rounded
                          ${getBadgeColor(alert.type)}
                        `}>
                          {alert.type.toUpperCase()}
                        </span>
                      </div>
                      <p className="text-xs text-zinc-400 leading-relaxed">
                        {alert.message}
                      </p>
                      {alert.metadata && (
                        <div className="mt-1 flex items-center gap-3 text-[10px] text-zinc-500">
                          {alert.metadata.value !== undefined && (
                            <span>Value: {alert.metadata.value}</span>
                          )}
                          {alert.metadata.threshold !== undefined && (
                            <span>Threshold: {alert.metadata.threshold}</span>
                          )}
                          {alert.metadata.change !== undefined && (
                            <span className={alert.metadata.change > 0 ? 'text-green-500' : 'text-red-500'}>
                              {alert.metadata.change > 0 ? '+' : ''}{alert.metadata.change}%
                            </span>
                          )}
                        </div>
                      )}
                    </div>
                    <span className="text-[10px] text-zinc-600 whitespace-nowrap">
                      {formatTime(alert.timestamp)}
                    </span>
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </AnimatePresence>

        {filteredAlerts.length === 0 && (
          <div className="text-center py-8 text-zinc-500">
            <Bell className="w-8 h-8 mx-auto mb-2 opacity-50" />
            <p className="text-sm">No alerts</p>
          </div>
        )}
      </div>
    </div>
  );
}
