"""
Strategy and backtesting data models.
"""
from dataclasses import dataclass, field
from decimal import Decimal
from datetime import datetime, timedelta
from typing import Literal, Optional, Any, Dict, List
from enum import Enum
import numpy as np


class OrderSide(str, Enum):
    BUY = "buy"
    SELL = "sell"


class SignalDirection(str, Enum):
    LONG = "long"
    SHORT = "short"
    CLOSE = "close"
    NEUTRAL = "neutral"


class PositionStatus(str, Enum):
    OPEN = "open"
    CLOSED = "closed"
    PENDING = "pending"


@dataclass
class PriceLevel:
    """Single price level in order book."""
    price: Decimal
    quantity: Decimal
    order_count: Optional[int] = None


@dataclass
class OrderBookSnapshot:
    """Order book snapshot at specific moment."""
    exchange: str
    symbol: str
    timestamp_us: int  # Microsecond precision
    sequence: int
    bids: List[PriceLevel]  # Sorted descending by price
    asks: List[PriceLevel]  # Sorted ascending by price

    @property
    def timestamp(self) -> datetime:
        """Convert microsecond timestamp to datetime."""
        return datetime.fromtimestamp(self.timestamp_us / 1_000_000)

    @property
    def mid_price(self) -> Decimal:
        """Calculate mid price."""
        if self.bids and self.asks:
            return (self.bids[0].price + self.asks[0].price) / 2
        return Decimal('0')

    @property
    def spread(self) -> Decimal:
        """Calculate bid-ask spread."""
        if self.bids and self.asks:
            return self.asks[0].price - self.bids[0].price
        return Decimal('0')

    def get_order_book_imbalance(self, levels: int = 5) -> float:
        """Calculate order book imbalance (OBI)."""
        bid_vol = sum(level.quantity for level in self.bids[:levels])
        ask_vol = sum(level.quantity for level in self.asks[:levels])

        total_vol = bid_vol + ask_vol
        if total_vol == 0:
            return 0.0

        return float((bid_vol - ask_vol) / total_vol)

    def get_vwap(self, side: str, quantity: Decimal) -> Optional[Decimal]:
        """Calculate volume-weighted average price for given quantity."""
        levels = self.asks if side == "buy" else self.bids
        remaining = quantity
        total_value = Decimal('0')

        for level in levels:
            if remaining <= 0:
                break

            fill_qty = min(remaining, level.quantity)
            total_value += fill_qty * level.price
            remaining -= fill_qty

        if remaining > 0:
            return None  # Not enough liquidity

        return total_value / quantity


@dataclass
class Trade:
    """Individual trade execution."""
    exchange: str
    symbol: str
    timestamp_us: int
    price: Decimal
    quantity: Decimal
    side: OrderSide  # Aggressor side
    trade_id: str

    @property
    def timestamp(self) -> datetime:
        """Convert microsecond timestamp to datetime."""
        return datetime.fromtimestamp(self.timestamp_us / 1_000_000)

    @property
    def value(self) -> Decimal:
        """Trade value in quote currency."""
        return self.price * self.quantity


@dataclass
class Alert:
    """Pattern detection alert."""
    id: str
    timestamp: datetime
    pattern: str  # "spoofing", "layering", "iceberg", etc.
    severity: Literal["info", "warning", "critical"]
    confidence: float  # 0.0 - 1.0
    exchange: str
    symbol: str
    context: Dict[str, Any]
    explanation: str
    ai_generated: bool = False


@dataclass
class Signal:
    """Trading signal generated by strategy."""
    timestamp: datetime
    direction: SignalDirection
    strength: float  # -1.0 to 1.0 (negative for short, positive for long)
    reason: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    target_price: Optional[Decimal] = None
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    position_size: Optional[Decimal] = None  # Suggested position size


@dataclass
class Position:
    """Trading position."""
    id: str
    symbol: str
    side: OrderSide
    entry_price: Decimal
    quantity: Decimal
    entry_time: datetime
    exit_price: Optional[Decimal] = None
    exit_time: Optional[datetime] = None
    status: PositionStatus = PositionStatus.OPEN
    pnl: Optional[Decimal] = None
    pnl_pct: Optional[float] = None
    commission_paid: Decimal = Decimal('0')
    slippage_cost: Decimal = Decimal('0')
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def value(self) -> Decimal:
        """Position value at entry."""
        return self.entry_price * self.quantity

    @property
    def is_open(self) -> bool:
        """Check if position is still open."""
        return self.status == PositionStatus.OPEN

    def close(self, exit_price: Decimal, exit_time: datetime, commission: Decimal = Decimal('0')):
        """Close the position."""
        self.exit_price = exit_price
        self.exit_time = exit_time
        self.status = PositionStatus.CLOSED
        self.commission_paid += commission

        # Calculate PnL
        if self.side == OrderSide.BUY:
            self.pnl = (exit_price - self.entry_price) * self.quantity - self.commission_paid - self.slippage_cost
        else:  # SHORT
            self.pnl = (self.entry_price - exit_price) * self.quantity - self.commission_paid - self.slippage_cost

        self.pnl_pct = float(self.pnl / self.value) * 100


@dataclass
class BacktestConfig:
    """Backtesting configuration."""
    initial_capital: Decimal = Decimal('10000')
    commission_bps: float = 10.0  # Basis points (0.1%)
    slippage_model: Literal["none", "fixed", "proportional", "order_book"] = "proportional"
    slippage_bps: float = 5.0  # For fixed/proportional models
    position_sizing: Literal["fixed", "kelly", "risk_parity", "equal_weight"] = "fixed"
    fixed_position_size: Decimal = Decimal('1000')  # For fixed sizing
    max_position_pct: float = 0.1  # Max % of capital per position
    max_positions: int = 10  # Maximum concurrent positions
    use_shorts: bool = True  # Allow short positions
    rebalance_frequency: Optional[timedelta] = None  # For portfolio strategies
    risk_free_rate: float = 0.02  # Annual risk-free rate for Sharpe/Sortino


@dataclass
class TradeRecord:
    """Record of executed trade in backtest."""
    timestamp: datetime
    symbol: str
    side: OrderSide
    quantity: Decimal
    price: Decimal
    commission: Decimal
    slippage: Decimal
    position_id: str
    signal: Signal

    @property
    def total_cost(self) -> Decimal:
        """Total cost including commission and slippage."""
        return self.price * self.quantity + self.commission + self.slippage


@dataclass
class PerformanceMetrics:
    """Comprehensive performance metrics."""
    # Returns
    total_return: float  # Percentage
    total_pnl: Decimal

    # Risk-adjusted returns
    sharpe_ratio: float
    sortino_ratio: float
    calmar_ratio: float

    # Risk metrics
    max_drawdown: float  # Percentage
    max_drawdown_duration: timedelta
    volatility: float  # Annualized
    downside_deviation: float
    var_95: float  # Value at Risk (95% confidence)
    cvar_95: float  # Conditional VaR

    # Trade statistics
    total_trades: int
    winning_trades: int
    losing_trades: int
    win_rate: float  # Percentage
    profit_factor: float  # Gross profit / Gross loss
    avg_win: Decimal
    avg_loss: Decimal
    avg_trade_pnl: Decimal
    best_trade_pnl: Decimal
    worst_trade_pnl: Decimal

    # Duration metrics
    avg_holding_period: timedelta
    max_holding_period: timedelta
    min_holding_period: timedelta

    # Activity metrics
    trades_per_day: float
    exposure_pct: float  # Average % of capital in market

    # Additional metrics
    recovery_factor: float  # Net profit / Max drawdown
    expectancy: Decimal  # Expected value per trade
    kelly_criterion: float  # Optimal position size

    def to_dict(self) -> Dict[str, Any]:
        """Convert metrics to dictionary."""
        return {
            'total_return': f"{self.total_return:.2f}%",
            'total_pnl': float(self.total_pnl),
            'sharpe_ratio': round(self.sharpe_ratio, 2),
            'sortino_ratio': round(self.sortino_ratio, 2),
            'calmar_ratio': round(self.calmar_ratio, 2),
            'max_drawdown': f"{self.max_drawdown:.2f}%",
            'max_drawdown_duration': str(self.max_drawdown_duration),
            'volatility': f"{self.volatility:.2f}%",
            'win_rate': f"{self.win_rate:.2f}%",
            'profit_factor': round(self.profit_factor, 2),
            'avg_win': float(self.avg_win),
            'avg_loss': float(self.avg_loss),
            'avg_trade_pnl': float(self.avg_trade_pnl),
            'total_trades': self.total_trades,
            'trades_per_day': round(self.trades_per_day, 2),
            'avg_holding_period': str(self.avg_holding_period),
            'exposure_pct': f"{self.exposure_pct:.2f}%",
            'kelly_criterion': f"{self.kelly_criterion:.2f}%",
        }


@dataclass
class BacktestResult:
    """Complete backtest results."""
    strategy_name: str
    config: BacktestConfig
    start_date: datetime
    end_date: datetime

    # Results
    trades: List[TradeRecord]
    positions: List[Position]
    equity_curve: List[tuple[datetime, Decimal]]  # (timestamp, equity value)
    metrics: PerformanceMetrics

    # Additional analysis
    daily_returns: List[float]
    monthly_returns: Dict[str, float]
    drawdown_periods: List[tuple[datetime, datetime, float]]  # Start, end, drawdown %

    def plot_equity_curve(self) -> Dict[str, Any]:
        """Generate equity curve plot data."""
        times = [t for t, _ in self.equity_curve]
        values = [float(v) for _, v in self.equity_curve]

        return {
            'x': times,
            'y': values,
            'type': 'line',
            'name': 'Equity Curve'
        }

    def plot_drawdown(self) -> Dict[str, Any]:
        """Generate drawdown plot data."""
        equity = np.array([float(v) for _, v in self.equity_curve])
        running_max = np.maximum.accumulate(equity)
        drawdown = (equity - running_max) / running_max * 100

        times = [t for t, _ in self.equity_curve]

        return {
            'x': times,
            'y': drawdown.tolist(),
            'type': 'area',
            'name': 'Drawdown %'
        }