"""Base Strategy ABC and Signal dataclass."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from typing import Literal, Any, Optional

from backend.app.models import OrderBookSnapshot, Trade, Alert


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    direction: Literal["long", "short", "close"]
    strength: float  # -1.0 to 1.0 (confidence/size hint)
    reason: str
    metadata: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)
    symbol: Optional[str] = None
    exchange: Optional[str] = None
    target_price: Optional[Decimal] = None
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None

    def __post_init__(self):
        """Validate signal strength."""
        if not -1.0 <= self.strength <= 1.0:
            raise ValueError(f"Signal strength must be between -1.0 and 1.0, got {self.strength}")


class Strategy(ABC):
    """Base class for all trading strategies."""

    def __init__(self, name: str = None):
        """Initialize strategy with optional name."""
        self.name = name or self.__class__.__name__
        self.position = None  # Will be set by backtester
        self.portfolio_value = Decimal('0')  # Will be updated by backtester
        self.state = {}  # Strategy-specific state

    @abstractmethod
    def on_book_update(self, book: OrderBookSnapshot) -> list[Signal]:
        """
        Process order book update and generate signals.

        Args:
            book: Current order book snapshot

        Returns:
            List of signals (can be empty)
        """
        pass

    @abstractmethod
    def on_trade(self, trade: Trade) -> list[Signal]:
        """
        Process trade event and generate signals.

        Args:
            trade: Executed trade

        Returns:
            List of signals (can be empty)
        """
        pass

    @abstractmethod
    def on_alert(self, alert: Alert) -> list[Signal]:
        """
        Process pattern detection alert and generate signals.

        Args:
            alert: Pattern detection alert

        Returns:
            List of signals (can be empty)
        """
        pass

    def on_position_update(self, position):
        """
        Called when position changes (optional override).

        Args:
            position: Current position object
        """
        self.position = position

    def on_portfolio_update(self, portfolio_value: Decimal):
        """
        Called when portfolio value changes (optional override).

        Args:
            portfolio_value: Current total portfolio value
        """
        self.portfolio_value = portfolio_value

    def reset(self):
        """Reset strategy state for new backtest run."""
        self.position = None
        self.portfolio_value = Decimal('0')
        self.state = {}